### ISSUE TITLE
XCode 12 : Could not find module ‘Apollo’ for target ‘arm64-apple-ios-simulator’; found: x86_64-apple-ios-simulator, x86_64

### ISSUE THREAD

**Issue by anuragfluke** [apollographql/xcode-graphql#35] opened 2020-10-06 13:11 UTC
Our product is created on XCode base 3.2, Recently moved on to XCode 11.6 with New build system.
 
Initially we were getting some issue with pods and carthage while importing Apollo framework but We have implemented Apollo framework successfully by Swift package manager.

Now we are moving to XCode 12 and getting error on simulator "Could not find module ‘Apollo’ for target ‘arm64-apple-ios-simulator’; found: x86_64-apple-ios-simulator, x86_64".

It is successfully compiling for iOS Device and Build... Only issue with running on simulator.

Possible solution tried till now - 
1)Adding arm64 in excluded architecture...errors are coming added screenshot. [
<img width="795" alt="Add Arm64 in exlude archi" src="https://user-images.githubusercontent.com/17405852/95205451-ff3bd480-0802-11eb-80be-e696350a9c33.png">
](url)

2)Add valid architecture in build settings  -  from **arm64 arm64e** to **arm64 arm64e x86_64** .... getting more errors.

It would be good if we can get some solution soon.

Thanks in advance. 

- [x] blocking
- [x] good first issue

@designatednerd @apollo-cla

**Comment by designatednerd** [comment] 2020-10-06 17:05
Hi! @anuragfluke can you please move this over to the [iOS SDK repo](https://github.com/apollographql/apollo-ios) since it's about the SDK rather than the plugin? Thank you! 

(short answer is I think the issue is that you need to change your included architectures `$(ARCHS_STANDARD)` and then update any _excluded_ architectures)

**Comment by designatednerd** [comment] 2020-11-13 04:31
Closing this out - please open an issue on the iOS SDK repo if you're still having problems. Thank you!

**Closed by designatednerd** 2020-11-13 04:31 UTC
