### ISSUE TITLE
Please add UUID to support Xcode 11

### ISSUE THREAD

**Issue by alistra** [apollographql/xcode-graphql#22] opened 2019-09-20 10:44 UTC
Currently the plugin doesn't work for Xcode 11

**Comment by Vuong-Dao** [comment] 2019-09-21 05:37
Yup. I got the same problem.

**Comment by designatednerd** [comment] 2019-09-21 15:33
Updated!

**Comment by Vuong-Dao** [comment] 2019-09-21 15:58
Hm, It didn't work for me on Version 11.0 (11A420a)
I downloaded a new source and ran it. And then choose "load bundle". But nothing happens when I open the file with graphql extension.

**Comment by designatednerd** [comment] 2019-09-21 16:08
@Vuong-Dao when you run `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID` at the command line, what UUID do you get?

**Comment by designatednerd** [comment] 2019-09-21 16:29
(I also would recommend the old Have You Tried Turning It Off And On Again thing - you almost certainly need to reboot Xcode before it'll work.

**Comment by designatednerd** [comment] 2019-09-21 17:25
I'm gonna close this for now but if you are getting a different UUID than the one added in [this commit](https://github.com/apollographql/xcode-graphql/commit/76c40a5c69895288d55dd657a4f1d965b31b9acf), please let me know ASAP. Please note this came from the version of 11.0 distributed through the Mac App Store, so it may differ from the ones on the GM versions.

**Closed by designatednerd** 2019-09-21 17:25 UTC

**Comment by selivandex** [comment] 2019-09-21 19:49
Same here on Version 11.0 (11A420a) 

I haven't seen xcode 11 in AppStore yet

**Comment by Vuong-Dao** [comment] 2019-09-22 02:19
Hi @designatednerd 
This is what I got: 2FD51EF8-522D-4532-9698-980C4C497FD1

Please note this came from the version of 11.0 distributed through the Mac App Store, so it may differ from the ones on the GM versions. => I'm using final Xcode came from App Store.

**Comment by designatednerd** [comment] 2019-09-23 18:35
@Vuong-Dao - Yep, that's exactly the UUID added [here](https://github.com/apollographql/xcode-graphql/commit/76c40a5c69895288d55dd657a4f1d965b31b9acf), so I'm not sure what the issue is. I would recommend redownloading and reinstalling.

**Comment by CraigSiemens** [comment] 2019-09-23 18:40
I've got the same issue as well. Xcode recognizes the file as a "GraphQL Query Document" but there is no syntax highlighting/formatting.

**Comment by Vuong-Dao** [comment] 2019-09-24 08:42
Should we re-open this issue? @designatednerd

**Comment by designatednerd** [comment] 2019-09-24 17:04
Nope, the UUID is working fine, the issue is Apple broke syntax highlighting by moving where things go in 11. Please follow #23 for further updates. Thank you!
